name: Deploy Backend (Functions)

on:
  workflow_dispatch:
    inputs:
      functionAppName:
        description: 'Function App name'
        required: true
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ github.event.inputs.functionAppName || 'wgspa-func' }}
          package: backend
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

      - name: Deployment Summary
        run: |
          echo "### Backend Deployed! ✅" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Function App: ${{ github.event.inputs.functionAppName || 'wgspa-func' }}" >> $GITHUB_STEP_SUMMARY
