name: Deploy SPA to Azure Static Web Apps

on:
  push:
    branches:
      - main
    paths:
      - 'index.html'
      - 'routes.json'
      - '.github/workflows/swa-deploy.yml'
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Deploy SPA

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Deploy to Azure Static Web Apps
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: '/' # Root of the repository
          output_location: '' # No build output, using CDN resources
          skip_app_build: true # No build step required

      - name: Deployment summary
        run: |
          echo "✅ SPA deployed successfully"
          echo "App location: /"
          echo "Using CDN resources: Foundation CSS + Alpine.js"
